/*----------------------------------------------------------------------
Name: 		IntegrationWrapper.cls
Purpose: 	A wrapper class of integration
------------------------------History----------------------------------
Version 	Author 		Date 				Detail Description 
-------		-------		-------------- 		------------------
1.0 		Abrar 		25-August-2017		Initial Development	
----------------------------------------------------------------------*/
public with sharing class IntegrationWrapper{

	public String firstName;
	public String lastName;
	public String emailAddress;
	public Boolean isActive;
	public Boolean isSuccess;
	// Other variables here...

	public IntegrationWrapper(){
		firstName = '';	
		firstName = '';	
		firstName = '';
		isActive = false;
		isSuccess = false;
		// Other variables here...
	}

}